export const ROUTES = {
  HOME: '/home',
  ABOUT: '/about',
  CONTACT_US: '/contact-us',
  DASHBOARD: '/dashboard',
  FORGOT_PASSWORD: '/forgot-password',
  CREATE_PASSWORD: '/create-password',
  LANDING: '/',
  LOGIN: '/login',
  CREATE_ACCOUNT: '/create-account',
  COUNTRYSECTION : '/create',
  PRIVACY_POLICY: '/privacy-policy',
  PROFILE: '/profile',
  SETTING: '/setting',
  SIGNUP: '/signup',
  VERIFY_DETAILS: '/verify-details',
  CREATE_SIGN_PASSWORD: '/create-sign-password',
  TERMS_CONDITION: '/terms-condition',
  USERS: '/users',
};
